[package]
name = "staticcc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
argparse = "0.2.2"
thiserror = "1.0.30"
comrak = "0.12.1"
fancy-regex = "0.10.0"
chrono = "0.4.19"
rss = "2.0.1"
